\input texinfo @c -*-texinfo-*-
@c %**start of header
@setfilename mpdired.info
@settitle MPDired Manual
@c %**end of header

@dircategory Emacs
@direntry
* MPDired: (mpdired).  A dired-like client for Music Player Daemon.
@end direntry
@copying
This file documents the MPDired package.

Copyright @copyright{} 2024, 2025 Free Software Foundation, Inc.

@quotation
The source and documentation of MPDired is free software.  You can
redistribute it and/or modify it under the terms of the GNU General
Public License as published by the Free Software Foundation; either
version 3, or (at your option) any later version.

MPDired is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License in
the file COPYING in the same directory as this file for more details.
@end quotation
@end copying

@titlepage
@set VERSION 3
@title MPDired Manual version @value{VERSION}
@author Manuel Giraud
@c  The following two commands
@c  start the copyright page.
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@contents

@ifnottex
@node Top
@top MPDired

@insertcopying
@end ifnottex

@menu
* Introdution::         What is MPDired?
* Connection::          Where to get the music?
* Queue::               What is playing?
* Browser::
* Philosphy::
* Index::
@end menu

@node Introdution
@chapter Introdution
@cindex introduction
@cindex intro
@cindex view
@findex mpdired-toggle-view

MPDired is an Emacs' client for the @uref{https://musicpd.org, Music
Player Daemon}.  Its interactions are inspired from
Dired. @xref{Dired,,,emacs}

It features two views packed into the same interactive buffer: the
queue view (@pxref{Queue}) and the browser view (@pxref{Browser}).
The queue view is where you see the songs that are playing or about to
play.  The browser view is where you see your songs' collection.

When in a MPDired buffer, you can switch from one view to the other
with @kbd{o} (@code{mpdired-toggle-view}).

But before being able to use MPDired, you should connect to your
@acronym{MPD, Music Player Daemon} server.

@node Connection
@chapter Connection
@vindex mpdired-host
@vindex mpdired-port
@findex mpdired

MPDired connects to a MPD server using two user options:
@code{mpdired-host} and @code{mpdired-port}.  Those options default to
your @env{MPD_HOST} and @env{MPD_PORT} environment variables or to
"localhost" and 6600 if these are not set.

If your have configured your MPD server to serve over a Unix domain
socket, you would use @code{mpdired-host} only and set it to this
socket's path.

When you have customized those options, you can start MPDired with

@example
@kbd{M-x mpdired @key{RET}}
@end example

Emacs pops you into a MPDired buffer connected to your
server@footnote{Once connected, the handle to the server is saved in a
buffer local variable.  From now on, MPDired only uses
@code{mpdired-host} and @code{mpdired-port} for global commands to
connect to the user's default server.  All commands used inside a
MPDired buffer will connect to the buffer local server instead.  This
way, you can manage more than one MPD server with multiple MPDired
buffers.}.  By default, the MPDired buffer displays the queue view.

@node Queue
@chapter Queue

The queue view is where you can see the list of songs queued and ready
to be played.  Here, you can manage this list.

The first line of the buffer shows some status information of the MPD
server: is it stopped, paused or playing?  If the latter, this line
also shows the current volume.

The remaining lines of the buffer show the songs, one for each line.
You can navigate this list with the following commands:

@table @kbd

@item n
@itemx C-n
@findex mpdired-next-line
Move to the next line.

@item p
@itemx C-p
@findex mpdired-previous-line
Move to the previous line.

@end table

In this view, when on a song's line, hitting @key{RET}
(@code{mpdired-enter}) will start playing this song.

@node Browser
@chapter Browser

@node Philosphy
@chapter Philosphy

This is a bit meta so I put this part as a later chapter.

MPDired is designed to be the least intrusive possible.  Nothing will
be shown into the mode line, which I consider to be user's territory.
There is also no timers set by MPDired, so updating anything always
comes from a user's action.

The browser view is built around the MPD's "listall" and
"listplaylists" commands.  The MPD's documentation does @strong{not}
recommend to do so but @acronym{AFAIU} there is no other way to access
your music collection in terms of directories and files.  As my own
music collection is already ordered into directories and with
meaningful filenames, I prefer to use this interface rather then to
rely on files' tags.

Be aware that if your music collection consists of just a set of not
very well named files into one big directory and that you rely on tags
such as "Genre", "Album", "Artist" to find your way through it then,
maybe, MPDired is not the right client for you.

@node Index
@unnumbered Index

@c Merge variable and function index into concept index.
@syncodeindex vr cp
@syncodeindex fn cp

@printindex cp

@bye
